INSERT INTO USERS VALUES (1, '김눈송', 'kimsnow', 'pass1234', 100, '[''TECHNOLOGY'', ''NOVEL'']', 'Y',CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USERS VALUES (2, '이바람', 'windlee', 'wind1234', 50, '[''LITERATURE'']', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USERS VALUES (3, '최별빛', 'starchoi', 'star5678', 20, '[''HISTORY'', ''SCIENCE'']', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USERS VALUES (4, '박햇살', 'sunpark', 'sun9999', 0, '[''SELF_DEVELOPMENT'']', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USERS VALUES (5, '장초롱', 'janglamp', 'light321', 10, '[''ECONOMY'']', 'N', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO LIBRARIES VALUES (1, '서울중앙도서관', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO LIBRARIES VALUES (2, '강남지점도서관', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO LIBRARIES VALUES (3, '부산해운대도서관', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO LIBRARIES VALUES (4, '제주동부도서관', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO LIBRARIES VALUES (5, '대전서구도서관', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- BOOKS 테이블 순서 수정: BOOK_ID, LIBRARY_ID, TITLE, AUTHOR, PUBLISHER, PUBLISHED_DATE, CATEGORY, AVAILABLE_AMOUNT, COVER_IMAGE, CALL_NUMBER, CREATED_AT, UPDATED_AT, BORROW_COUNT, STATUS
INSERT INTO BOOKS VALUES (1, 2, '내게 남은 스물다섯 번의 계절', '슈테판 셰퍼', '서삼독', TO_TIMESTAMP('2021-02-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'NOVEL', 5, 'https://image.aladin.co.kr/product/36387/54/cover500/k702039674_1.jpg', '101.B1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 43, 'AVAILABLE');
INSERT INTO BOOKS VALUES (2, 3, '제2차 냉전 시대', '제이슨 솅커', '더페이지', TO_TIMESTAMP('2022-03-03 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ECONOMY', 9, 'https://image.aladin.co.kr/product/36319/60/cover500/k382038542_1.jpg', '102.C2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4, 'AVAILABLE');
INSERT INTO BOOKS VALUES (3, 4, '데이타베이스 프로그래밍 길잡이', '심준호', '21세기사', TO_TIMESTAMP('2020-04-04 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'TECHNOLOGY', 6, 'https://image.aladin.co.kr/product/607/23/cover500/8984683388_1.jpg', '103.D3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 49, 'AVAILABLE');
INSERT INTO BOOKS VALUES (4, 5, '꾸준한 행복', '김신회', '여름사람', TO_TIMESTAMP('2021-05-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'LITERATURE', 5, 'https://image.aladin.co.kr/product/36415/49/cover500/k812039999_1.jpg', '104.E4', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8, 'AVAILABLE');
INSERT INTO BOOKS VALUES (5, 1, '고래눈이 내리다', '김보영', '래빗홀', TO_TIMESTAMP('2022-06-06 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'NOVEL', 5, 'https://image.aladin.co.kr/product/36423/24/cover500/k162039192_1.jpg', '105.F5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 30, 'AVAILABLE');
INSERT INTO BOOKS VALUES (6, 2, '물질의 세계', '에드 콘웨이', '인플루엔셜(주)', TO_TIMESTAMP('2020-07-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HISTORY', 2, 'https://image.aladin.co.kr/product/33478/66/cover500/k992938150_3.jpg', '106.G6', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 34, 'AVAILABLE');
INSERT INTO BOOKS VALUES (7, 3, '인생의 연금술', '이하영', '웅진지식하우스', TO_TIMESTAMP('2021-08-08 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SELF_DEVELOPMENT', 8, 'https://image.aladin.co.kr/product/36490/23/cover500/8901294850_1.jpg', '107.H7', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12, 'AVAILABLE');
INSERT INTO BOOKS VALUES (8, 4, '완전 건강 상담소', '조승우', '알에이치코리아(RHK)', TO_TIMESTAMP('2022-09-09 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HEALTH', 4, 'https://image.aladin.co.kr/product/36527/2/cover500/8925573571_2.jpg', '108.I8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 42, 'AVAILABLE');
INSERT INTO BOOKS VALUES (9, 5, '현명한 투자자1', '벤저민 그레이엄', '국일증권경제연구소', TO_TIMESTAMP('2020-10-10 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'ECONOMY', 10, 'https://image.aladin.co.kr/product/36492/27/cover500/8957822402_1.jpg', '109.J9', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 'AVAILABLE');
INSERT INTO BOOKS VALUES (10, 1, '수면의 뇌과학', '크리스 윈터', '현대지성', TO_TIMESTAMP('2021-11-11 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'SCIENCE', 0, 'https://image.aladin.co.kr/product/36458/92/cover500/k612039715_1.jpg', '110.K10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6, 'AVAILABLE');

--INSERT INTO LOANS VALUES (1, 1, 1, TO_TIMESTAMP('2025-06-12 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), NULL, 0, 'BORROWED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--INSERT INTO LOANS VALUES (2, 2, 2, TO_TIMESTAMP('2025-06-05 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-13 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), 1, 'RETURNED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--INSERT INTO LOANS VALUES (3, 3, 3, TO_TIMESTAMP('2025-06-10 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), NULL, 2, 'OVERDUE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO RESERVATIONS (RESV_ID, USER_ID, BOOK_ID, RESV_DATE, STATUS, CREATED_AT, UPDATED_AT)
VALUES (1, 4, 4, CURRENT_TIMESTAMP, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO RESERVATIONS (RESV_ID, USER_ID, BOOK_ID, RESV_DATE, STATUS, CREATED_AT, UPDATED_AT)
VALUES (2, 5, 5, CURRENT_TIMESTAMP, 'CANCELLED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO RESERVATIONS (RESV_ID, USER_ID, BOOK_ID, RESV_DATE, STATUS, CREATED_AT, UPDATED_AT)
VALUES (3, 2, 6, CURRENT_TIMESTAMP, 'COMPLETED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO READING_LOG VALUES (1, 1, 1, TO_TIMESTAMP('2025-06-08 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-14 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), 5, 100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO READING_LOG VALUES (2, 2, 2, TO_TIMESTAMP('2025-06-01 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-10 03:19:26', 'YYYY-MM-DD HH24:MI:SS'), 10, 80, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 중복 방지를 위한 MERGE 구문 사용
MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 1 as user_id, 'TECHNOLOGY' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 1 as user_id, 'NOVEL' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 2 as user_id, 'LITERATURE' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 3 as user_id, 'HISTORY' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 3 as user_id, 'SCIENCE' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 4 as user_id, 'SELF_DEVELOPMENT' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);

MERGE INTO USER_PREFERRED_CATEGORIES target
USING (SELECT 5 as user_id, 'ECONOMY' as category FROM dual) source
ON (target.user_id = source.user_id AND target.category = source.category)
WHEN NOT MATCHED THEN INSERT (user_id, category) VALUES (source.user_id, source.category);