-- Oracle SQL
--noinspection SqlDialectInspectionForFile

-- 시퀀스 생성
CREATE SEQUENCE user_seq
    START WITH 6
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE book_seq
    START WITH 11
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE library_seq
    START WITH 6
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE loan_seq
    START WITH 101
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE resv_seq
    START WITH 4
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE log_seq
    START WITH 3
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE passbook_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 도서관 테이블 생성
CREATE TABLE LIBRARIES(
    LIBRARY_ID NUMBER,
    NAME VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LIBRARIES PRIMARY KEY (LIBRARY_ID)
);

-- 사용자 테이블 생성
CREATE TABLE USERS (
    USER_ID NUMBER,
    USER_NAME VARCHAR2(50) NOT NULL,
    LOGIN_ID VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    MILEAGE NUMBER DEFAULT 0 NOT NULL,
    INTERESTS VARCHAR2(4000),  -- JSON 배열 형태로 저장
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UK_USERS_LOGIN_ID UNIQUE (LOGIN_ID),
    CONSTRAINT CK_USERS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CK_USERS_MILEAGE CHECK (MILEAGE >= 0)
);

-- 도서 테이블 생성
CREATE TABLE BOOKS (
    BOOK_ID NUMBER(19) NOT NULL,
    LIBRARY_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    AUTHOR VARCHAR2(100) NOT NULL,
    PUBLISHER VARCHAR2(100),
    PUBLISHED_DATE TIMESTAMP,
    CATEGORY VARCHAR2(30) NOT NULL,
    AVAILABLE_AMOUNT NUMBER(10) DEFAULT 1 NOT NULL,
    COVER_IMAGE VARCHAR2(500),
    CALL_NUMBER VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    borrow_count NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'AVAILABLE',
    CONSTRAINT PK_BOOKS PRIMARY KEY (BOOK_ID),
    CONSTRAINT FK_BOOKS_LIBRARY_ID
        FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARIES(LIBRARY_ID),
    CONSTRAINT CK_BOOKS_CATEGORY
        CHECK (CATEGORY IN ('HEALTH','ECONOMY','SCIENCE','TECHNOLOGY',
        'LITERATURE','NOVEL', 'HISTORY','SELF_DEVELOPMENT')),
    CONSTRAINT CK_BOOKS_AVAILABLE_AMOUNT
        CHECK (AVAILABLE_AMOUNT >= 0)
);

-- 대출 테이블 생성
CREATE TABLE LOANS (
    LOAN_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    BORROW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RETURN_DATE TIMESTAMP,
    EXTEND_NUMBER NUMBER DEFAULT 0,
    STATUS VARCHAR2(20) DEFAULT 'BORROWED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_LOANS PRIMARY KEY (LOAN_ID),
    CONSTRAINT FK_LOANS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_LOANS_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT CK_LOANS_EXTEND_NUMBER CHECK (EXTEND_NUMBER >= 0 AND EXTEND_NUMBER <= 2),
    CONSTRAINT CK_LOANS_STATUS CHECK (STATUS IN ('BORROWED','RETURNED','RESERVED','OVERDUE'))
);

-- 예약 테이블 생성
CREATE TABLE RESERVATIONS (
    RESV_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    RESV_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_RESERVATIONS PRIMARY KEY (RESV_ID),
    CONSTRAINT FK_RESERVATIONS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_RESERVATIONS_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT CK_RESERVATIONS_STATUS CHECK (STATUS IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

-- 독서 로그 테이블 생성
CREATE TABLE READING_LOG (
    LOG_ID NUMBER,
    USER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    BORROW_DATE TIMESTAMP NOT NULL,
    RETURN_DATE TIMESTAMP,
    MILEAGE NUMBER DEFAULT 0,
    TOTAL_MILEAGE NUMBER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_READING_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_READING_LOG_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT FK_READING_LOG_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    CONSTRAINT CK_READING_LOG_MILEAGE CHECK (MILEAGE >= 0),
    CONSTRAINT CK_READING_LOG_TOTAL_MILEAGE CHECK (TOTAL_MILEAGE >= 0)
);

-- 사용자 선호 카테고리 테이블 생성
CREATE TABLE USER_PREFERRED_CATEGORIES (
    USER_ID NUMBER NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_USER_PREFERRED_CATEGORIES PRIMARY KEY (USER_ID, CATEGORY),
    CONSTRAINT FK_UPC_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINT CK_UPC_CATEGORY CHECK (CATEGORY IN ('HEALTH','ECONOMY','SCIENCE','TECHNOLOGY',
        'LITERATURE','NOVEL', 'HISTORY','SELF_DEVELOPMENT'))
);
